### ISSUE TITLE
serde_cbor allows duplicate keys in map

### ISSUE THREAD

**Issue by petreeftime** [pyfisch/cbor#143]
This is not exactly a bug, but it's undefined behavior which I think should result in a parsing error: https://tools.ietf.org/html/rfc7049#section-3.4 or at least there should be a way for a user of serde_cbor to be able to discern if a map inside a CBOR object is malformed.

```
use serde_cbor;
use std::collections::BTreeMap;

fn main() {
    let data: Vec<u8> = vec![ 0xA2, // Map of two elements
        0x01, // Key: 1
        0x42, 0x61, 0x61, // Value: "aa"
        0x01, // Key: 1
        0x42, 0x62, 0x62 // Value: "bb"
    ];
    let map: BTreeMap<u8, String> = serde_cbor::from_slice(&data).unwrap();
    println!("{:?}", map);
}
```
prints out
```
{1: "bb"}
```

serde_cbor should check when inserting a new key if key is not already in use and emit a parsing error.

This is relevant because certain other specs require stricter behavior, for example COSE specifies that the same key cannot be reused, and there's no way to tell from serde_cbor if this is true as far as I can tell. See https://tools.ietf.org/html/rfc8152#section-14.

**Comment by pyfisch** [comment]
> This is not exactly a bug, but it's undefined behavior

Actually it is implementation defined behavior. The spec outlines a few different options (only one value, error) and serde-cbor chose one of them.

> serde_cbor should check when inserting a new key if key is not already in use and emit a parsing error.

One issue with this is that you need to keep around all map keys and compare each key to the previous keys. This incurs a performance penality and therefore an opt-out should be offered.

If you use a `struct`, instead of a map, serde will error on duplicate keys. (I think)
Another option is to implement deserialize yourself for a map-like type and check for duplicate keys.

(How does serde-json handle duplicate keys?)

**Comment by petreeftime** [comment]
I found something related in serde: https://github.com/serde-rs/serde/pull/916. I'm not sure I figured out the solution yet from the discussion, but implementing my own Deserialize might be a solution.

**Comment by petreeftime** [comment]
This seems like a generic serde feature, so I will close the issue in this repo.
