### ISSUE TITLE
Deserialize multiple objects

### ISSUE THREAD

**Issue by masche842** [pyfisch/cbor#20]
I'm using serde_cbor in a linux fifo to pass commands from one daemon to another. When the receiving daemon is not fast enough and two structures are put into the fifo, cbor fails with "TrailingBytes". 

Therefore it would be helpful to have a method that returns the size of bytes that have already been decoded. With that information, i.e. an iterator could be implemented.

Maybe such functionality is already in the pipeline?

**Comment by masche842** [comment]
So, after implementing the actual Iterator, I figured that having the Read trait is enough. No need to know the position.

What about adding an Iterator implementation to cbor? Is this of interest?

**Comment by pyfisch** [comment]
You want to add an iterator to CBOR that counts the bytes decoded?

**Comment by masche842** [comment]
No, an iterator that adds capability to parse multiple Objects from one slice. 
I have a working implementation in my project. It looks like this:
https://gist.github.com/masche842/d87f82aa093ad9b5cd8743915d6d3f2c

**Comment by pyfisch** [comment]
Sorry for the delay. Now I think, I undersnd what you want.

In [RFC 7049](https://tools.ietf.org/html/rfc7049) terms you have a data stream:

>   Data Stream:  A sequence of zero or more data items, not further
>      assembled into a larger containing data item.  The independent
>      data items that make up a data stream are sometimes also referred
>      to as "top-level data items".

The data stream is already read into a slice and is then iterated over (as in the example code).

The question I have is, what happens if the slice does contain an incomplete object? The example code indicates no object is returned in this case. But since calls to Read consume the buffer it is not possible to read the object at a later time because the start of it is lost. Even worse the following objects also can’t be decoded because the rest of the preceding object is still in the fifo stream.

I am open to add support for "data streams" to the cbor crate but they will need to handle partial reads. One possible solution is to read all available data into a buffer first and to only remove bytes from the buffer after an object was completed.

There is also a short section on [CBOR in Streaming Applications](https://tools.ietf.org/html/rfc7049#section-3.1) in the RFC that basically describes what I mentioned before.

Does this also apply to your use case or are you sure only complete objects will ever be in your fifo or you close the fifo after the first unexpected EOF?

**Comment by masche842** [comment]
Sorry for not answering, totally forgot about it.

You are right, this indeed is an issue. I'm used my implementation for half a year now and it worked flawlessly, but theoretically it's possible that the fifo is read while the other application still writes it - leaving things in an inconsistent state. 

I will revise some mechanisms in my system anyway (it's an embedded linux device), then I will take care of that issue too. I'll let you know when I've come up with a more solid implementation.

**Comment by pyfisch** [comment]
No problem. Thanks for your reply. Feel free to reopen this issue when when you are revising the CBOR handling or have a better implementation.
