### ISSUE TITLE
RecursionLimitExceeded

### ISSUE THREAD

**Issue by artjoma** [pyfisch/cbor#219]
Deserialize huge struct: Error: ` ErrorImpl { code: RecursionLimitExceeded, offset: 30094 }' `

Serde json support https://docs.rs/serde_json/1.0.64/serde_json/struct.Deserializer.html#method.disable_recursion_limit :
```
deserializer.disable_recursion_limit();
```

How I can increase recursion limit ?

**Comment by pyfisch** [comment]
It is fixed in the code and I don't accept pull requests at this time.

Currently serde-cbor accepts 128 levels of recursion which is more than sufficient for most use cases. Are you sure the document is well-formed? You can maintain a private fork of this crate and change the relevant lines. https://github.com/pyfisch/cbor/blob/a218403a52e60c991313f429e4acc05cce81ce25/src/de.rs#L189

It may be configurable in ciborium https://github.com/enarx/ciborium
