### ISSUE TITLE
Upgrade to serde 1.0

### ISSUE THREAD

**Issue by sfackler** [pyfisch/cbor#29]

**Comment by pyfisch** [comment]
I am working on this.

**Comment by pyfisch** [comment]
Ok, I've updated cbor to serde 1.0 and all tests pass. Can you please have a look at the code before I release? (There is an alpha version on crates.io)

PS: I currently do not use this crate but it got somewhat popular. Because I do not have this much time any more it would be great if someone else would maintain it. Maybe it can live at the serde-rs organization? After serde has reached 1.0 there are probably not that many updates needed.

**Comment by sfackler** [comment]
Thanks!

@dtolnay thoughts on a transfer to the serde org? ^

**Comment by dtolnay** [comment]
I would prefer not to transfer to the serde-rs org because I don't have the bandwidth to own this crate. IIRC this crate is pretty important to you, can you or someone on the team own it?

**Comment by dtolnay** [comment]
@pyfisch the bound on `from_reader` should be `T: DeserializeOwned` - see [this page](https://serde.rs/lifetimes.html#trait-bounds). Also it would be great to support zero-copy deserialization as part of this. That involves `parse_string` and `parse_bytes` calling `visit_borrowed_str` and `visit_borrowed_bytes` if the input is a `&'de [u8]`.

**Comment by dtolnay** [comment]
Perhaps @BurntSushi could take over in lieu of implementing https://github.com/BurntSushi/rust-cbor/issues/3?

**Comment by jq-rs** [comment]
Hi! I think CBOR is quite similar with JSON so in that sense serde-rs would be a logical place. Unfortunate if it does not fit there. As a crate user I'd appreciate a long term solution anyway.

**Comment by sfackler** [comment]
I'd be happy to poke at supporting zero copy deserialization, but it'd be great to get a release with the changes you've already made in the mean time.

**Comment by pyfisch** [comment]
Released as [v0.6.0](https://crates.io/crates/serde_cbor/0.6.0).

**Comment by pyfisch** [comment]
Remaining work filed as #31 and #32.

**Comment by sfackler** [comment]
Awesome, thank you!
