### ISSUE TITLE
Override `is_human_readable`

### ISSUE THREAD

**Issue by tailhook** [pyfisch/cbor#51]
According to the docs when [`is_human_readable`](https://docs.rs/serde/1.0.23/serde/trait.Serializer.html#method.is_human_readable) is `false` serializer can produce more compact and efficient form. I think this is what expected from cbor serializer. (default is `true`)

Unfortunately changing it is a breaking change, but I think it's okay in zero-point release.

So I'll make a PR, if you're fine with it?

Alternative would be to make it configurable, but I don't think human-readable things in binary cbor is a good default.

**Comment by pyfisch** [comment]
Can you explain what `is_human_readable` changes? I mean CBOR is pretty much unreadable unless you are used to reading punch cards.

If it is no big change maybe you can submit the PR so I can better understand it?

**Comment by sfackler** [comment]
`is_human_readable` states that your format isn't human readable. `Serialize` implementations can use this to switch to more compact encodings of themselves. For example, a UUID will normally serialize as the string `123e4567-e89b-12d3-a456-426655440000`, but if `is_human_readable` is false, it'll serialize as the raw bytes. This ends up being 16 bytes rather than 36.

**Comment by pyfisch** [comment]
@sfackler thanks for the explanation. In this case I am all for it even if is a a breaking change.
