### ISSUE TITLE
Use of forward_to_deserialize_any! leads to surprising visitor calls

### ISSUE THREAD

**Issue by TimNN** [pyfisch/cbor#84]
I was attempting to (de-)serialize an enum from an integer, as described in https://serde.rs/enum-number.html.

When deserializing, I got the somewhat confusing error message ``invalid type: integer `1`, expected [My Enum]``.

The issue is, as I found out later, that `cbor` uses `forward_to_deserialize_any!`. The implementation of `deserialize_any()` then visits the integer type actually encoded in the data rather than the requested / originally encoded type (in my case `u8` is visited rather than `u32`).

This behavior was very surprising to me. I could not find anything conclusive in the serde docs about how the deserializer should behave in this case, however ignoring the explicitly requested type seems wrong to me.

**Comment by sfackler** [comment]
@dtolnay what's the right thing to do here? Should we have a bunch of visitors that internally do the right cast?

**Comment by dtolnay** [comment]
Serde_json also currently gives you its own choice of integer type rather than the one that the Deserialize impl asks for.

I agree with @TimNN, it would be helpful for the Deserializer to handle the conversion. I would be open to providing a Visitor wrapper in the serde crate to perform the conversion to a preferred integer type. Something like:

```rust
fn deserialize_u32<V>(self, visitor: V) -> Result<V::Value>
where
    V: Visitor<'de>,
{
    deserialize_cbor_number(self, ConvertNumbers::to::<u32>(visitor))
}
```

and maybe update forward_to_deserialize_any to use it, after thinking through whether this would break any code.

**Comment by pyfisch** [comment]
This does not seem to come up often.
